### PR TITLE
Option to not add step to check if workflow id up to date

### PR DESCRIPTION
**Pull request by awoimbee**
relates to #18

I also removed dead code.
Feel free to edit without asking first.

### CODE REVIEW

**Comment by mithro** [comment]
Looks like the CI is broken on pull requests....

**Comment by mithro** [comment]
Can you try rebasing onto master?

**Comment by mithro** [comment]
So as far as I can see, you have not updated `actions_includes/check.py` which calls `expand_workflow`. I'm not sure why this didn't cause something to fail....

**Comment by mithro** [comment]
I /think/ I have fixed the main branch so it should detect the check issue. I have rebased onto the latest and I guess we will see shortly....

**Comment by mithro** [comment]
https://github.com/mithro/actions-includes/pull/22/checks?check_run_id=2181664407
```
Run ./.github/includes/actions/local
Building docker image
/usr/bin/docker run --name e4199e13ab21355c64b456594e8387c8bf_205178 --label 5588e4 --workdir /github/workspace --rm -e pythonLocation -e LD_LIBRARY_PATH -e INPUT_WORKFLOW -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/actions-includes/actions-includes":"/github/workspace" 5588e4:199e13ab21355c64b456594e8387c8bf  ".github/workflows/test.actions-ifexpands.yml"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/github/workspace/actions_includes/check.py", line 95, in <module>
Downloading: https://raw.githubusercontent.com/mithro/actions-includes/54c7b7c26b17e1f586434a7c66d1bd2be306a371/.github/workflows/test.actions-ifexpands.yml
    sys.exit(main(sys.argv))
  File "/github/workspace/actions_includes/check.py", line 66, in main
    workflow_src = actions_includes.RemoteFilePath(USER, REPO, SHA, str(workflow_srcpath)[1:])
AttributeError: module 'actions_includes' has no attribute 'RemoteFilePath'
```

**Comment by mithro** [comment]
@awoimbee Do you want to take a look at fixing that?

**Comment by awoimbee** [comment]
Sorry for not making this PR nice the first time
And BTW: thanks for this project, it's really helpful

**Review by mithro — APPROVED** [review]
LGTM!

Thank you for contributing here.

**Pull request merged**
